import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  docs: [
    "intro",
    "authentication",
    "webhooks",
    "update-shipping-api",
    {
      type: "category",
      label: "Products",
      items: [
        "create-product-api",
        "update-product-api",
        "get-product-by-id",
        "get-all-products",
      ],
    },
    {
      type: "category",
      label: "Categories",
      items: [
        "create-category",
        "get-all-categories",
        "get-category-by-id",
        "update-category-by-id",
      ],
    },
    {
      type: "category",
      label: "Orders",
      items: ["get-order-by-id", "update-order-status", "add-order-notes"],
    },
    "rate-limit",
    "permissions",
    "create_authorized_app_link",
    "connect-dropshipping",
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
